// Copyright (c) 2020 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// VirtualMachineListerExpansion allows custom methods to be added to
// VirtualMachineLister.
type VirtualMachineListerExpansion interface{}

// VirtualMachineNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineNamespaceLister.
type VirtualMachineNamespaceListerExpansion interface{}

// VirtualMachineClassListerExpansion allows custom methods to be added to
// VirtualMachineClassLister.
type VirtualMachineClassListerExpansion interface{}

// VirtualMachineImageListerExpansion allows custom methods to be added to
// VirtualMachineImageLister.
type VirtualMachineImageListerExpansion interface{}

// VirtualMachineServiceListerExpansion allows custom methods to be added to
// VirtualMachineServiceLister.
type VirtualMachineServiceListerExpansion interface{}

// VirtualMachineServiceNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineServiceNamespaceLister.
type VirtualMachineServiceNamespaceListerExpansion interface{}

// VirtualMachineSetResourcePolicyListerExpansion allows custom methods to be added to
// VirtualMachineSetResourcePolicyLister.
type VirtualMachineSetResourcePolicyListerExpansion interface{}

// VirtualMachineSetResourcePolicyNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineSetResourcePolicyNamespaceLister.
type VirtualMachineSetResourcePolicyNamespaceListerExpansion interface{}
